Añadir fichero CONTRIBUTING.md
pythoncanarias/pycan-web pull request #370
Opened 2021-09-22 17:49 UTC by euribates

Fixes #369

2021-09-22 20:44 UTC, jdevera requested changes

2021-09-22 20:44 UTC, jdevera commented on CONTRIBUTING.md
> +explica como montar un entorno de desarrollo propio unsado _Docker_ y
```suggestion
explica cómo montar un entorno de desarrollo propio usando _Docker_ y
```

2021-09-22 20:44 UTC, jdevera commented on CONTRIBUTING.md
> +para formatear el código, pero no se considera obligatorio.
Podríamos pasarlo todo por black con el ancho de linea a 96 y pedirlo a partir de ahí sistemáticamente para todo. Incluso validarlo en una github action.

2021-09-22 20:44 UTC, jdevera commented on CONTRIBUTING.md
> +Intentamos (Pero no siempre conseguimos) mantener el código de los modelos y de
```suggestion
Intentamos (pero no siempre conseguimos) mantener el código de los modelos y de
```

2021-09-22 20:44 UTC, jdevera commented on CONTRIBUTING.md
> +aplicación.
Esto queda demasiado descolgado o teórico, estaría bien un ejemplo, quizá.

2021-09-22 20:44 UTC, jdevera commented on CONTRIBUTING.md
> +### Todas las aplicaciones están en la carpeta `apps`
```suggestion
### Organización de código de las aplicaciones de Django
```

En los títulos hay una mezcla de estilos, algunos son frases nominales, otros declaraciones, otros órdenes. Voy a sugerir unificar en en el primer caso.

2021-09-22 20:44 UTC, jdevera commented on CONTRIBUTING.md
> +Como hay muchas aplicaciones o _apps_, se trasladaron todas a una única
```suggestion
Como hay muchas aplicaciones o _apps_, las tenemos todas todas bajo una única
```
Define el estado sin hablar del proceso histórico.

2021-09-22 20:44 UTC, jdevera commented on CONTRIBUTING.md
> +carpeta `apps`, para reducir la cantidad de _ruido_ que se encontraba en
```suggestion
carpeta `apps`, para reducir la cantidad de _ruido_  en
```

2021-09-22 20:44 UTC, jdevera commented on CONTRIBUTING.md
> +si pedimos que analices primero si las ventajas de usar esa nueva librería
```suggestion
sí que pedimos que analices primero si las ventajas de usar esa nueva librería
```

2021-09-22 20:44 UTC, jdevera commented on CONTRIBUTING.md
> +dependencias frena las actualizaciones generales, que es un objetivo que
Esto convendría explicarlo un poco más.

2021-09-22 20:44 UTC, jdevera commented on CONTRIBUTING.md
> +### Mantener la lógica de negocio fuera de los modelos y de las vistas
```suggestion
### Separación entre lógica de negocio, modelos y vistas
```

2021-09-22 20:44 UTC, jdevera commented on CONTRIBUTING.md
> +### Asigna nombres únicos a ficheros, clases y funciones
```suggestion
### Nombres de ficheros, clases y funciones
```

2021-09-22 20:44 UTC, jdevera commented on CONTRIBUTING.md
> +cada entidad con nombre en nuestro código debería tener un nombre único.
Empieza la frase con esta línea, y sigue con la anterior, va al punto primero, y luego mete la excepción. También cambiaría "Excepción hecha de" por "exceptuando".

2021-09-22 20:44 UTC, jdevera commented on CONTRIBUTING.md
> +Hay muchas razones para esto, pero veamos por ejemplo las clases. Si nos
Esto me parece bastante artificial. Además va un poco tambíen en contra de la idea de los bounded contexts del Domain Driven Design que casi se está aplicando por la división de apps de Django.

Herramientas dummy de búsqueda de texto como grep y familia no deberían ser un hilo conductor para cambiar la nomenclatura. Es más importante que el código se entienda bien cuando se lee y el caso de uso de búsqueda está mejor cubierto con herramientas con algo más de inteligencia del lenguaje, como un IDE. La semántica que carga un nombre está en gran parte en el nombre en sí, pero hay una parte fundamental que es el entorno en el que se encuentra, y creo que es el mismo principio por el cual está bien repetir nombres de variables locales.

Yo quitaría esta restricción por completo.

2021-09-22 20:44 UTC, jdevera commented on CONTRIBUTING.md
> +### Preferimos funciones antes que clases
```suggestion
### Funciones vs clases para vistas
```

2021-09-22 20:44 UTC, jdevera commented on CONTRIBUTING.md
> +En general, recomendamos usar funciones para las vistas, mejor que vistas
```suggestion
Para las vistas, preferimos, en general, usar funciones en vez de vistas
```

2021-09-22 20:44 UTC, jdevera commented on CONTRIBUTING.md
> +prohibición de usar _CBV_, Es solo que preferimos usarlas para casos sencillos
```suggestion
prohibición de usar _CBV_, es solo que preferimos usarlas para casos sencillos
```

2021-09-22 20:44 UTC, jdevera commented on CONTRIBUTING.md
> +y/o triviales, y usar funciones para todo lo demás.
No entiendo, usamos clases para cosas sencillas pero funciones para cosas complicadas?

2021-09-24 07:21 UTC, euribates commented on CONTRIBUTING.md
> +para formatear el código, pero no se considera obligatorio.
Si, es una idea que se comento, nunca llegamos a implementrla, pero quiza podriamos aprovechar el Hacktoberfest

2021-09-24 07:24 UTC, euribates commented on CONTRIBUTING.md
> +Hay muchas razones para esto, pero veamos por ejemplo las clases. Si nos
Mas que una restriccion es una recomendacion, pero estoy de acuerdo en que no todo el mundo tiene que estar de acuerdo con esto. Quiza lo mejor sea quitarlo todo, si.O quiza mantenerlo por lo menos para los nombres de las clases.

2021-09-24 07:25 UTC, euribates commented on CONTRIBUTING.md
> +aplicación.
Si, es buedna idea, voy a ver si encuentro algún ejemplo sencillo y lo incluyo

2021-10-04 16:23 UTC, euribates commented on CONTRIBUTING.md
> +Hay muchas razones para esto, pero veamos por ejemplo las clases. Si nos
Suavizada la recomendacion solo para clases y constantes/variables globales

2021-10-04 16:24 UTC, euribates commented on CONTRIBUTING.md
> +aplicación.
Hecho

2021-10-04 16:24 UTC, euribates commented on CONTRIBUTING.md
> +y/o triviales, y usar funciones para todo lo demás.
Exacto

2021-10-04 16:29 UTC, euribates commented on CONTRIBUTING.md
> +dependencias frena las actualizaciones generales, que es un objetivo que
Next release

2021-10-04 16:31 UTC, merged