Nuevo doc de primeros pasos
pythoncanarias/pycan-web pull request #376
Opened 2021-10-04 18:03 UTC by euribates

Fixes #375

2021-10-04 20:22 UTC, jdevera requested changes

2021-10-04 20:22 UTC, jdevera commented on docs/primeros_pasos.md
> +Lo primero que necesitas es un conocimiento, aunque sea básico, de git y GitHub.
```suggestion
Lo primero que necesitas es un conocimiento, aunque sea básico, de Git y GitHub.
```

2021-10-04 20:22 UTC, jdevera commented on docs/primeros_pasos.md
> +repositorio. Esta _fork_ es simplemente una copia de nuestro repositorio, que
```suggestion
repositorio. Este _fork_ es simplemente una copia de nuestro repositorio, que
```

2021-10-04 20:22 UTC, jdevera commented on docs/primeros_pasos.md
> +con tu cuenta, y simplemente y visita con tu navegador nuestra repositorio.
```suggestion
con tu cuenta, y simplemente y visita con tu navegador nuestro repositorio.
```

2021-10-04 20:22 UTC, jdevera commented on docs/primeros_pasos.md
> +![Github Fork](github-fork.png)
Iba a poner que esto mejor en assets, y también que no está en esta PR, pero en realidad voy a recomendar borrar esta línea.

2021-10-04 20:22 UTC, jdevera commented on docs/primeros_pasos.md
> +los pruebas si puedes y las vas añadiendo a la rama. Puedes usar `git status` para
```suggestion
los pruebas si puedes y los vas añadiendo a la rama. Puedes usar `git status` para
```

2021-10-04 20:22 UTC, jdevera commented on docs/primeros_pasos.md
> +los commits que quieres, pero si es verdad que el paso previo a subir el código
```suggestion
los commits que quieras, pero si es verdad que el paso previo a subir el código
```

2021-10-04 20:22 UTC, jdevera commented on docs/primeros_pasos.md
> +### Séptimo paso, importar o entregar (_push_) los cambios locales al repositorio.
```suggestion
### Séptimo paso, exportar o entregar (_push_) los cambios locales al repositorio.
```
Si decimos importar estamos yendo a contracorriente de cómo usa git los puntos de referencia. Un push está empujando algo hacia fuera.

2021-10-04 20:22 UTC, jdevera commented on docs/primeros_pasos.md
> +Una vez que tus cambios están en tu repositorio, estás listos para
```suggestion
Una vez que tus cambios están en tu repositorio, están listos para
```

2021-10-04 20:22 UTC, jdevera commented on docs/primeros_pasos.md
> +incorporar los cambios incluidos en una rama en concreto un otra rama,
```suggestion
incorporar los cambios incluidos en una rama en concreto a otra rama,
```

2021-10-04 20:22 UTC, jdevera commented on docs/primeros_pasos.md
> +hicimos _fork_ al comienzo.
No soy capaz de parsear este párrafo. Prueba a leerlo en voz alta, hay algo raro.

2021-10-05 17:05 UTC, euribates commented on docs/primeros_pasos.md
> +![Github Fork](github-fork.png)
Se me habia pasado inckuirlo en el repo, ya esta en assets

2021-10-05 17:28 UTC, euribates commented on docs/primeros_pasos.md
> +hicimos _fork_ al comienzo.
Modificado

2021-10-05 17:30 UTC, merged